# migrate-2assets.ps1
# Migrate to 2-asset structure

Write-Host "=" * 70 -ForegroundColor Green
Write-Host "SETTING UP 2-ASSET STRUCTURE" -ForegroundColor Green
Write-Host "=" * 70 -ForegroundColor Green
Write-Host ""

# Step 1: Create folders
Write-Host "Step 1: Creating asset folders..." -ForegroundColor Cyan
New-Item -ItemType Directory -Path "docs-industrial-ai" -Force | Out-Null
New-Item -ItemType Directory -Path "docs-digital-thread" -Force | Out-Null
Write-Host "  Created: docs-industrial-ai" -ForegroundColor Green
Write-Host "  Created: docs-digital-thread" -ForegroundColor Green

# Step 2: Move AOT files to Industrial AI
Write-Host "`nStep 2: Moving AOT files..." -ForegroundColor Cyan
$aotFiles = Get-ChildItem -Path "docs" -Filter "AOT_*.md"
Write-Host "  Found $($aotFiles.Count) files"

if ($aotFiles.Count -gt 0) {
    foreach ($file in $aotFiles) {
        Move-Item -Path $file.FullName -Destination "docs-industrial-ai\" -Force
        Write-Host "  Moved: $($file.Name)" -ForegroundColor Green
    }
} else {
    Write-Host "  No files found to move" -ForegroundColor Yellow
}

# Step 3: Create intro files
Write-Host "`nStep 3: Creating intro pages..." -ForegroundColor Cyan

$industrialAiIntro = @"
---
sidebar_position: 1
title: Industrial AI Foundation
---

# Industrial AI Foundation

Platform documentation for asset monitoring and optimization.

Browse the sidebar to explore available documentation.

[Back to Home](/)
"@

Set-Content -Path "docs-industrial-ai\intro.md" -Value $industrialAiIntro
Write-Host "  Created: docs-industrial-ai\intro.md" -ForegroundColor Green

$digitalThreadIntro = @"
---
sidebar_position: 1
title: Digital Thread Foundations
---

# Digital Thread Foundations

Integration framework documentation.

*Documentation coming soon*

[Back to Home](/)
"@

Set-Content -Path "docs-digital-thread\intro.md" -Value $digitalThreadIntro
Write-Host "  Created: docs-digital-thread\intro.md" -ForegroundColor Green

# Step 4: Create sidebar files
Write-Host "`nStep 4: Creating sidebar files..." -ForegroundColor Cyan

$industrialAiSidebar = @"
module.exports = {
  industrialAiSidebar: [{type: 'autogenerated', dirName: '.'}],
};
"@

Set-Content -Path "sidebars-industrial-ai.js" -Value $industrialAiSidebar
Write-Host "  Created: sidebars-industrial-ai.js" -ForegroundColor Green

$digitalThreadSidebar = @"
module.exports = {
  digitalThreadSidebar: [{type: 'autogenerated', dirName: '.'}],
};
"@

Set-Content -Path "sidebars-digital-thread.js" -Value $digitalThreadSidebar
Write-Host "  Created: sidebars-digital-thread.js" -ForegroundColor Green

Write-Host "`n" + ("=" * 70) -ForegroundColor Green
Write-Host "SETUP COMPLETE!" -ForegroundColor Green
Write-Host ("=" * 70) -ForegroundColor Green
Write-Host "`nNext steps:" -ForegroundColor Cyan
Write-Host "  1. Replace docusaurus.config.js"
Write-Host "  2. Replace docs\intro.md"
Write-Host "  3. Run: npm start"
Write-Host ""
